config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :posts
  get 'stylists' => 'posts#stylists'
  get 'scrubs' => 'posts#scrubs'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  resourcify
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :find_stylists

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def stylists
    @users = User.all
  end

  def scrubs
    @users = User.all
  end

  # GET /posts/new
  def new
    not_authorised and return unless current_user.can_create?
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    not_authorised and return unless current_user.can_update?(@post)
  end

  # POST /posts
  # POST /posts.json
  def create
    not_authorised and return unless current_user.can_create?

    @post = Post.new(post_params)
    @post.user = current_user
    assign_owner_role

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    not_authorised and return unless current_user.can_update?(@post)

      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    not_authorised and return unless current_user.can_destroy?(@post)

      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :image, :is_stylist)
    end

    def not_authorised
      flash[:notice] = "You are not authorised!"
      redirect_to posts_path
    end

    def find_stylists
    @users = User.all
    @stylists = @users.with_role(:stylist)
    end 

    def assign_owner_role
      if @post.user.has_role?(:stylist)
        @post.owner_role = "stylist"
      elsif @post.user.has_role?(:scrub)
        @post.owner_role = "scrub"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>      
      <th>Image</th>
      <th>Is stylist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.content %></td>        
        <td><%= post.image %></td>
        <td><%= post.user.is_stylist %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user.can_update?(post) %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <% if current_user.can_destroy?(post) %>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/scrubs.html.erb
<h1>Scrubs</h1>


<% @users.each do |user| %>
  <% if user.has_role?(:scrub) %>
    <%= user.email %>
    <%= link_to 'Profile', profile_path(user)%><br />
    <br>    
  <% end %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>Is stylist:</strong>
  <%= @post.user.is_stylist %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/stylists.html.erb
<h1>Stylists</h1>


<% @users.each do |user| %>
  <% if user.has_role?(:stylist) %>
    <p><%= user.email %></p>
  <% end %>
<% end %>